on: push
name: Python Checkout
jobs:
  Flake8:
    runs-on: ubuntu-latest
    name: Flake8 syntax check
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
  E2E Check:
    runs-on: ubuntu-latest
    name: E2E check
    run: python3 ./test_executor/tests/test_e2e.py