on: push
name: Python Checkout
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Flake8 syntax check
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
  pytest:
    runs-on: ubuntu-latest
    name: Pytest passing tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pytest Action Step
        id: pytest
        uses: paolorechia/fast-pytest-github-action@develop
        with:
          pytest_args: 'tests/'
